package try_catch_block;

public class Program2 {
	public static void main(String[] args) {
		System.out.println("Program2 Started");
		throw new ArithmeticException("divided by zero!!");
	}

}
